# Generated by Django 3.2.3 on 2021-05-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estanteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50, verbose_name='Nombre del Modelo')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('precio', models.FloatField(verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Estantenria',
                'verbose_name_plural': 'Estanterias',
            },
        ),
    ]
