# Generated by Django 2.2.3 on 2021-05-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaPlastica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('altura', models.FloatField(verbose_name='Altura CM')),
                ('base', models.FloatField(verbose_name='Base CM')),
                ('fondo', models.FloatField(verbose_name='Fondo CM')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('piezas', models.IntegerField(default=0, verbose_name='Cantidad Piezas')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=50, verbose_name='Nombre del Modelo')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('piezas', models.IntegerField(default=0, verbose_name='Cantidad Piezas')),
                ('espacios', models.IntegerField(default=0, verbose_name='Cantidad Espacios')),
            ],
            options={
                'verbose_name': 'Locker',
                'verbose_name_plural': 'Lockers',
            },
        ),
        migrations.CreateModel(
            name='MueblesOficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=50, verbose_name='Nombre del Mueble')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('piezas', models.IntegerField(default=0, verbose_name='Cantidad Piezas')),
            ],
            options={
                'verbose_name': 'Mueble',
                'verbose_name_plural': 'Muebles',
            },
        ),
        migrations.RenameField(
            model_name='estanteria',
            old_name='modelo',
            new_name='nombre_modelo',
        ),
        migrations.AddField(
            model_name='estanteria',
            name='piezas',
            field=models.IntegerField(default=0, verbose_name='Cantidad Piezas'),
        ),
        migrations.AlterField(
            model_name='estanteria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
